Simulationblog/config/routes.rb
Rails.application.routes.draw do

  resources :comments
  resources :articles
  devise_for :users
  devise_scope :users do
    root to: "devise/sessions#new"
  end

  resources :articles do
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:show]

end

Simulationblog/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end


    user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :create, Article
        can :create, Comment
        can :read, :all
        can :manage, Article, :user_id => user.id
        can :destroy, Comment, :user_id => user.id
        if user.moderator?
          can :destroy, Comment
        end
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

Simulationblog/app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments
	belongs_to :user
end

Simulationblog/app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :article
end

Simulationblog/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

require 'carrierwave/orm/activerecord'

  has_many :articles
  has_many :comments

	enum role: [ :author, :moderator, :admin ]
  
  #mount_uploader :avatar, AvatarUploader
  
  before_create :define_role

  def define_role
  	self.role = "author" unless self.role.present?
  end




end

Simulationblog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :lastname, :identification, :profession, :username, :describe_yourself, :avatar, :role ])
  end


end

Simulationblog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  @comment = Comment.new(article: @article)
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    
    @article.user = current_user

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:date, :user_id, :title, :content)
    end
end

Simulationblog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  
  def create
    @comment = Comment.new(comment_params)
    
    @comment.user = current_user
    @comment.article_id = params[:article_id]
    
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.article, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { redirect_to root_path, notice: 'Your comment had errors.' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end



  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:date, :user_id, :article_id, :content)
    end
end

Simulationblog/app/controllers/user_controller.rb
class UserController < ApplicationController

	def show
		@user = User.find(params[:id])
	end

end

Simulationblog/app/helpers/application_helper.rb
module ApplicationHelper
end

Simulationblog/app/helpers/articles_helper.rb
module ArticlesHelper
end

Simulationblog/app/helpers/comments_helper.rb
module CommentsHelper
end

Simulationblog/app/helpers/user_helper.rb
module UserHelper
end

Simulationblog/app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Simulationblog/app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

Simulationblog/app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>



<h1>Articles</h1>

<% @articles.each do |article| %>
  <article>
    <%= link_to article do %>
      <h2><%= article.title %></h2>
    <% end %>
    
    <%= link_to article.user do %>
      <span><%= article.user.username %></span>
    <% end %>
    
    <p><%= simple_format(truncate(article.content, length: 200) )%></p>
    <% if can? :manage, article %>
      <%= link_to 'Edit', edit_article_path(article) %>
      <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  
  </article>
    
   
<% if user_signed_in?%>

<%= current_user.email %>

<%= link_to "logout", destroy_user_session_path, method: :delete %>

<%end%>



   
<% end %>


<br>

<%= link_to 'Write new article', new_article_path %>

Simulationblog/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

Simulationblog/app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>


<h1><strong><%= @article.title %></strong></h1>
<%= link_to @article.user do %>
  <span><%= @article.user.username %></span>
<% end %>

<p><%= simple_format(@article.content) %></p>

<h2>Write your comment:</h2>
<%= render 'comments/form' %>

<br>

<% @article.comments.each do |comment|%>
	<article>
	<h3><%= comment.user.username%> said:</h3>
	<p><%= simple_format(comment.content) %></p>
	<% if can? :destroy, comment %>	
	<%= link_to 'Destroy', article_comment_path(@article, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
	<% end %>
	</article>
<% end %>

Simulationblog/app/views/comments/_form.html.erb
<%= form_for(@comment, url: article_comments_path(@article), method: :post) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<% if user_signed_in?%>

<%= current_user.email %>

<%= link_to "logout", destroy_user_session_path, method: :delete %>

<%end%>

Simulationblog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simulationblog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
<% end %>


<%= yield %>

</body>
</html>

Simulationblog/app/views/user/show.html.erb
<h1><%= @user.name %></h1>
<p><%= @user.articles.count %> articles</p>
<p><%= simple_format(@user.description)%></p>

<h2>Articles</h2>
<ul>
	<% @user.articles.each do |article| %>
    <li><%= link_to article.title, article %></li>
	<% end%>
</ul>

<h2>Comments</h2>

<ul>
  <% @user.comments.each do |comment| %>
    <li><%= link_to comment.article.title, comment.article %>: <%= truncate(comment.content)%></li>
  <% end%>
</ul>

<% if user_signed_in?%>

<%= current_user.email %>

<%= link_to "logout", destroy_user_session_path, method: :delete %>

<%end%>